### ISSUE TITLE
Error in extension `myurl.com/premium`

### ISSUE THREAD

**Issue by TajuModding** [dhvitOP/Discord-Bot-List-with-Servers-List#1]
Got this error when  trying to go there
```js
TypeError: /home/runner/bot/src/views/botlist/apps/premium.ejs:1
 >> 1| <%- include('../../parts/head', {bot, user, path}) %>
    2| <title>Premium | Discord Bots</title>
    3| <div class="container px-3 mt-2 pt-5">
    4|     <div class="container px-3 content is-widescreen pt-5">

/home/runner/bot/src/views/parts/head.ejs:84
    82|                     <% } %>
    83|                    
 >> 84|                    <% 
    85|                 let guild = bot.guilds.cache.get(config.server.id).members.cache.get(user.id);
    86|                 if(guild) {
    87|                 if(guild.roles.cache.get(roles.yonetici) || guild.roles.cache.get(roles.moderator)) {

Cannot read property 'members' of undefined
    at eval (eval at compile (/home/runner/bot/node_modules/ejs/lib/ejs.js:662:12), <anonymous>:36:67)
    at head (/home/runner/bot/node_modules/ejs/lib/ejs.js:692:17)
    at include (/home/runner/bot/node_modules/ejs/lib/ejs.js:690:39)
    at eval (eval at compile (/home/runner/bot/node_modules/ejs/lib/ejs.js:662:12), <anonymous>:8:17)
    at premium (/home/runner/bot/node_modules/ejs/lib/ejs.js:692:17)
    at tryHandleCache (/home/runner/bot/node_modules/ejs/lib/ejs.js:272:36)
    at View.exports.renderFile [as engine] (/home/runner/bot/node_modules/ejs/lib/ejs.js:489:10)
    at View.render (/home/runner/bot/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/runner/bot/node_modules/express/lib/application.js:640:10)
    at Function.render (/home/runner/bot/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/home/runner/bot/node_modules/express/lib/response.js:1012:7)
    at renderTemplate (/home/runner/bot/src/server.js:87:9)
    at /home/runner/bot/src/server.js:1713:9
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by dhvitOP** [comment]
just server id is wrong or the bot is not added to the given server id in config

**Comment by TajuModding** [comment]
and this is edited form of vcodes right?

**Comment by dhvitOP** [comment]
yes
but modified and added Servers List, Vanity,Team, Premium, News all on my own
